spring: 
    profiles: 
        active: 
            -dev
---
spring: 
    profiles: dev
    application: 
        name: compoment-config-dev
---
spring: 
    profiles: test
    application: 
        name: compoment-config-test